# fly.toml app configuration file generated for audit-rules on 2026-03-10T21:14:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'audit-rules'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  PROJECT_ROOT = '/app'

[[mounts]]
  source = 'db_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
